const Blogs = [
  {
    id: 1,
    title: "Travel 1",
    author: "Rajesh",
    read: "10 min read",
    claps: 300,
    category: "Travel",
    image:
      "https://cdn.pixabay.com/photo/2015/10/30/20/13/sunrise-1014712_960_720.jpg",
    date: "January 1 2022",
    text: `Aliquip nisi cillum esse nulla.Consectetur eu cupidatat dolor et magna laborum commodo qui aliqua culpa eu enim. Tempor enim nulla aute sunt exercitation excepteur consectetur dolore sint minim. Tempor irure eu fugiat sint et consectetur proident est nostrud.`,
    tags: ["Travel"],
  },
  {
    id: 2,
    title: "Travel 2",
    author: "AShraf",
    read: "10 min read",
    claps: 270,
    category: "Travel",
    image:
      "https://cdn.pixabay.com/photo/2021/12/05/10/28/nature-6847175_960_720.jpg",
    date: "January 1 2022",
    text: `Aliquip nisi cillum esse nulla.Consectetur eu cupidatat dolor et magna laborum commodo qui aliqua culpa eu enim. Tempor enim nulla aute sunt exercitation excepteur consectetur dolore sint minim. Tempor irure eu fugiat sint et consectetur proident est nostrud.`,
    tags: ["Travel"],
  },
  {
    id: 3,
    title: "Travel 3",
    author: "Rajesh",
    read: "10 min read",
    claps: 310,
    category: "Travel",
    image:
      "https://cdn.pixabay.com/photo/2016/11/29/09/16/architecture-1868667_960_720.jpg",
    date: "January 1 2022",
    text: `Aliquip nisi cillum esse nulla.Consectetur eu cupidatat dolor et magna laborum commodo qui aliqua culpa eu enim. Tempor enim nulla aute sunt exercitation excepteur consectetur dolore sint minim. Tempor irure eu fugiat sint et consectetur proident est nostrud.`,
    tags: ["Travel"],
  },

  {
    id: 4,
    title: "Bollywood 1",
    author: "Rajesh",
    read: "10 min read",
    claps: 400,
    category: "Bollywood",
    image:
      "https://media.istockphoto.com/photos/bollywood-picture-id689019358?b=1&k=20&m=689019358&s=170667a&w=0&h=jqgI_5R3XpiV_5G_o8SgLUm_v6HPpzMXxqS9C6DSFJM=",
    date: "January 12 2022",
    text: `Aliquip nisi cillum esse nulla.Consectetur eu cupidatat dolor et magna laborum commodo qui aliqua culpa eu enim. Tempor enim nulla aute sunt exercitation excepteur consectetur dolore sint minim. Tempor irure eu fugiat sint et consectetur proident est nostrud.`,
    tags: ["bollywood", "India", "entertainment"],
  },
  {
    id: 5,
    title: "Bollywood 2",
    author: "Rajesh",
    read: "10 min read",
    claps: 100,
    category: "Bollywood",
    image:
      "https://upload.wikimedia.org/wikipedia/en/c/c3/Haathi_Mere_Saathi.jpg",
    date: "January 1 2022",
    text: ` STORY: Captain Kapil Dev led a team from India, seen as underdogs, to bring home the country’s first-ever World Cup title in the year 1983. Kabir Khan’s ‘83’ encapsulates the journey of this team that taught a nation to believe and to pin its hopes on its cricket players’ by returning home as a set of uniquely gifted world champions.`,
    tags: ["bollywood", "India", "entertainment"],
  },
  {
    id: 6,
    title: "Bollywood 3",
    author: "Rajesh",
    read: "10 min read",
    claps: 900,
    category: "Bollywood",
    image:
      "https://images.unsplash.com/photo-1477591546808-36d4a193cbc2?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE0fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` STORY: Captain Kapil Dev led a team from India, seen as underdogs, to bring home the country’s first-ever World Cup title in the year 1983. Kabir Khan’s ‘83’ encapsulates the journey of this team that taught a nation to believe and to pin its hopes on its cricket players’ by returning home as a set of uniquely gifted world champions.`,
    tags: ["bollywood", "India", "entertainment"],
  },
  {
    id: 7,
    title: "Bollywood 4",
    author: "Rajesh",
    read: "10 min read",
    claps: 355,
    category: "Bollywood",
    image:
      "https://images.unsplash.com/photo-1603909477416-3fc943f3e4d8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1yZWxhdGVkfDE4fHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` STORY: Captain Kapil Dev led a team from India, seen as underdogs, to bring home the country’s first-ever World Cup title in the year 1983. Kabir Khan’s ‘83’ encapsulates the journey of this team that taught a nation to believe and to pin its hopes on its cricket players’ by returning home as a set of uniquely gifted world champions.`,
    tags: ["bollywood", "India", "entertainment"],
  },
  {
    id: 8,
    title: "Bollywood 5",
    author: "Rajesh",
    read: "10 min read",
    claps: 430,
    category: "Bollywood",
    image:
      "https://images.unsplash.com/photo-1505921393400-6bdca0e00764?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxjb2xsZWN0aW9uLXBhZ2V8MTJ8MjYwMjEwNHx8ZW58MHx8fHw%3D&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` STORY: Captain Kapil Dev led a team from India, seen as underdogs, to bring home the country’s first-ever World Cup title in the year 1983. Kabir Khan’s ‘83’ encapsulates the journey of this team that taught a nation to believe and to pin its hopes on its cricket players’ by returning home as a set of uniquely gifted world champions.`,
    tags: ["bollywood", "India", "entertainment"],
  },
  {
    id: 9,
    title: "Technology 1",
    author: "Rajesh",
    read: "10 min read",
    claps: 400,
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8dGVjaG5vbG9neXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Excepteur et laboris et fugiat cupidatat pariatur nulla nisi proident mollit laborum. Sunt adipisicing nulla consequat et eu nostrud ipsum ullamco nulla. Ipsum nostrud est esse cupidatat et nostrud officia qui commodo tempor occaecat exercitation excepteur. Ut nisi magna eu dolore sint pariatur sunt amet Lorem laborum enim excepteur. Adipisicing adipisicing minim ut excepteur adipisicing esse aute laboris ipsum. Nulla cupidatat aliqua anim est fugiat nisi cupidatat non quis non. Lorem culpa mollit tempor nostrud occaecat cillum cupidatat id velit.`,
    tags: ["Technology", "Tech"],
  },
  {
    id: 10,
    title: "Technology 2 ",
    author: "Rajesh",
    read: "10 min read",
    claps: 400,
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8dGVjaG5vbG9neXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Excepteur et laboris et fugiat cupidatat pariatur nulla nisi proident mollit laborum. Sunt adipisicing nulla consequat et eu nostrud ipsum ullamco nulla. Ipsum nostrud est esse cupidatat et nostrud officia qui commodo tempor occaecat exercitation excepteur. Ut nisi magna eu dolore sint pariatur sunt amet Lorem laborum enim excepteur. Adipisicing adipisicing minim ut excepteur adipisicing esse aute laboris ipsum. Nulla cupidatat aliqua anim est fugiat nisi cupidatat non quis non. Lorem culpa mollit tempor nostrud occaecat cillum cupidatat id velit.`,
    tags: ["Technology", "Tech"],
  },
  {
    id: 11,
    title: "Technology 3 ",
    author: "Rajesh",
    read: "10 min read",
    claps: 100,
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1485827404703-89b55fcc595e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NHx8dGVjaG5vbG9neXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    text: ` Excepteur et laboris et fugiat cupidatat pariatur nulla nisi proident mollit laborum. Sunt adipisicing nulla consequat et eu nostrud ipsum ullamco nulla. Ipsum nostrud est esse cupidatat et nostrud officia qui commodo tempor occaecat exercitation excepteur. Ut nisi magna eu dolore sint pariatur sunt amet Lorem laborum enim excepteur. Adipisicing adipisicing minim ut excepteur adipisicing esse aute laboris ipsum. Nulla cupidatat aliqua anim est fugiat nisi cupidatat non quis non. Lorem culpa mollit tempor nostrud occaecat cillum cupidatat id velit.`,
    tags: ["Technology", "Tech"],
  },
  {
    id: 12,
    title: "Technology 4 ",
    author: "Rajesh",
    read: "10 min read",
    claps: 100,
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1526666923127-b2970f64b422?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTZ8fHRlY2hub2xvZ3l8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Excepteur et laboris et fugiat cupidatat pariatur nulla nisi proident mollit laborum. Sunt adipisicing nulla consequat et eu nostrud ipsum ullamco nulla. Ipsum nostrud est esse cupidatat et nostrud officia qui commodo tempor occaecat exercitation excepteur. Ut nisi magna eu dolore sint pariatur sunt amet Lorem laborum enim excepteur. Adipisicing adipisicing minim ut excepteur adipisicing esse aute laboris ipsum. Nulla cupidatat aliqua anim est fugiat nisi cupidatat non quis non. Lorem culpa mollit tempor nostrud occaecat cillum cupidatat id velit.`,
    tags: ["Technology", "Tech"],
  },
  {
    id: 13,
    title: "Technology 5 ",
    author: "Rajesh",
    read: "10 min read",
    claps: 100,
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1535223289827-42f1e9919769?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MjB8fHRlY2hub2xvZ3l8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Excepteur et laboris et fugiat cupidatat pariatur nulla nisi proident mollit laborum. Sunt adipisicing nulla consequat et eu nostrud ipsum ullamco nulla. Ipsum nostrud est esse cupidatat et nostrud officia qui commodo tempor occaecat exercitation excepteur. Ut nisi magna eu dolore sint pariatur sunt amet Lorem laborum enim excepteur. Adipisicing adipisicing minim ut excepteur adipisicing esse aute laboris ipsum. Nulla cupidatat aliqua anim est fugiat nisi cupidatat non quis non. Lorem culpa mollit tempor nostrud occaecat cillum cupidatat id velit.`,
    tags: ["Technology", "Tech"],
  },
  {
    id: 14,
    title: "Technology 6 ",
    author: "Rajesh",
    read: "10 min read",
    claps: 690,
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mzl8fHRlY2hub2xvZ3l8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Excepteur et laboris et fugiat cupidatat pariatur nulla nisi proident mollit laborum. Sunt adipisicing nulla consequat et eu nostrud ipsum ullamco nulla. Ipsum nostrud est esse cupidatat et nostrud officia qui commodo tempor occaecat exercitation excepteur. Ut nisi magna eu dolore sint pariatur sunt amet Lorem laborum enim excepteur. Adipisicing adipisicing minim ut excepteur adipisicing esse aute laboris ipsum. Nulla cupidatat aliqua anim est fugiat nisi cupidatat non quis non. Lorem culpa mollit tempor nostrud occaecat cillum cupidatat id velit.`,
    tags: ["Technology", "Tech"],
  },
  {
    id: 15,
    title: "Hollywood 1",
    author: "Rajesh",
    read: "10 min read",
    claps: 700,
    category: "Hollywood",
    image:
      "https://images.unsplash.com/photo-1590452522688-e919e18c9e96?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTB8fGhvbGx5d29vZHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Hollywood", "English"],
  },
  {
    id: 16,
    title: "Hollywood 2",
    author: "Rajesh",
    read: "10 min read",
    claps: 300,
    category: "Hollywood",
    image:
      "https://images.unsplash.com/photo-1534253893894-10d024888e49?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Hollywood", "English"],
  },
  {
    id: 17,
    title: "Hollywood 3",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Hollywood",
    image:
      "https://media.istockphoto.com/photos/welcome-to-hollywood-picture-id487316718?b=1&k=20&m=487316718&s=170667a&w=0&h=9bgbd_AtxysrODpgVjc4vqb2Enqbs4bgXMbXwewgkt8=",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Hollywood", "English"],
  },
  {
    id: 18,
    title: "Hollywood 4",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Hollywood",
    image:
      "https://images.unsplash.com/photo-1560343776-97e7d202ff0e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435&q=80",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Hollywood", "English"],
  },
  {
    id: 19,
    title: "Bollywood 6",
    author: "Rajesh",
    read: "10 min read",
    claps: 430,
    category: "Bollywood",
    image:
      "https://stat1.bollywoodhungama.in/wp-content/uploads/2022/01/K.G.F-%E2%80%93-Chapter-2-480x270.jpg",
    date: "January 1 2022",
    text: ` STORY: Captain Kapil Dev led a team from India, seen as underdogs, to bring home the country’s first-ever World Cup title in the year 1983. Kabir Khan’s ‘83’ encapsulates the journey of this team that taught a nation to believe and to pin its hopes on its cricket players’ by returning home as a set of uniquely gifted world champions.`,
    tags: ["bollywood", "India", "entertainment"],
  },
  {
    id: 20,
    title: "Bollywood 7",
    author: "Rajesh",
    read: "10 min read",
    claps: 430,
    category: "Bollywood",
    image:
      "https://www.filmcompanion.in/wp-content/uploads/2020/06/film-companion-govinda-Lead-image-2.jpg",
    date: "January 1 2022",
    text: ` STORY: Captain Kapil Dev led a team from India, seen as underdogs, to bring home the country’s first-ever World Cup title in the year 1983. Kabir Khan’s ‘83’ encapsulates the journey of this team that taught a nation to believe and to pin its hopes on its cricket players’ by returning home as a set of uniquely gifted world champions.`,
    tags: ["bollywood", "India", "entertainment"],
  },
  {
    id: 21,
    title: "Bollywood 8",
    author: "Rajesh",
    read: "10 min read",
    claps: 430,
    category: "Bollywood",
    image:
      "https://media.gqindia.com/wp-content/uploads/2020/05/Best-%E2%80%9890s-Bollywood-movies-10-stars-reveal-their-favourite-movies-from-the-decade-stream-them-on-Netflix-Amazon-Prime-Video-SonyLiv.jpg",
    date: "January 1 2022",
    text: ` STORY: Captain Kapil Dev led a team from India, seen as underdogs, to bring home the country’s first-ever World Cup title in the year 1983. Kabir Khan’s ‘83’ encapsulates the journey of this team that taught a nation to believe and to pin its hopes on its cricket players’ by returning home as a set of uniquely gifted world champions.`,
    tags: ["bollywood", "India", "entertainment"],
  },
  {
    id: 22,
    title: "Technology 7 ",
    author: "Rajesh",
    read: "10 min read",
    claps: 690,
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjd8fHRlY2hub2xvZ3l8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Excepteur et laboris et fugiat cupidatat pariatur nulla nisi proident mollit laborum. Sunt adipisicing nulla consequat et eu nostrud ipsum ullamco nulla. Ipsum nostrud est esse cupidatat et nostrud officia qui commodo tempor occaecat exercitation excepteur. Ut nisi magna eu dolore sint pariatur sunt amet Lorem laborum enim excepteur. Adipisicing adipisicing minim ut excepteur adipisicing esse aute laboris ipsum. Nulla cupidatat aliqua anim est fugiat nisi cupidatat non quis non. Lorem culpa mollit tempor nostrud occaecat cillum cupidatat id velit.`,
    tags: ["Technology", "Tech"],
  },
  {
    id: 23,
    title: "Technology 8 ",
    author: "Rajesh",
    read: "10 min read",
    claps: 690,
    category: "Technology",
    image:
      "https://images.unsplash.com/photo-1423784346385-c1d4dac9893a?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    date: "January 1 2022",
    text: ` Excepteur et laboris et fugiat cupidatat pariatur nulla nisi proident mollit laborum. Sunt adipisicing nulla consequat et eu nostrud ipsum ullamco nulla. Ipsum nostrud est esse cupidatat et nostrud officia qui commodo tempor occaecat exercitation excepteur. Ut nisi magna eu dolore sint pariatur sunt amet Lorem laborum enim excepteur. Adipisicing adipisicing minim ut excepteur adipisicing esse aute laboris ipsum. Nulla cupidatat aliqua anim est fugiat nisi cupidatat non quis non. Lorem culpa mollit tempor nostrud occaecat cillum cupidatat id velit.`,
    tags: ["Technology", "Tech"],
  },
  {
    id: 24,
    title: "Hollywood 5",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Hollywood",
    image:
      "https://images.unsplash.com/photo-1579445710183-f9a816f5da05?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=429&q=80",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Hollywood", "English"],
  },
  {
    id: 25,
    title: "Hollywood 6",
    author: "Rajesh",
    read: "10 min read",
    claps: 1200,
    category: "Hollywood",
    image:
      " https://images.unsplash.com/photo-1608889175123-8ee362201f81?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Hollywood", "English"],
  },
  {
    id: 26,
    title: "Hollywood 7",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Hollywood",
    image:
      " https://images.unsplash.com/photo-1561149877-84d268ba65b8?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=435&q=80",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Hollywood", "English"],
  },
  {
    id: 27,
    title: "Fitness 1",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Fitness",
    image:
      "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Fit", "Healthy"],
  },
  {
    id: 28,
    title: "Fitness 2",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Fitness",
    image:
      "https://images.unsplash.com/photo-1494597564530-871f2b93ac55?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=813&q=80",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Fit", "Healthy"],
  },
  {
    id: 29,
    title: "Fitness 3",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Fitness",
    image:
      "https://images.unsplash.com/photo-1535743686920-55e4145369b9?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1332&q=80",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Fit", "Healthy"],
  },
  {
    id: 30,
    title: "Fitness 4",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Fitness",
    image:
      "https://images.unsplash.com/photo-1483721310020-03333e577078?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mjl8fGZpdG5lc3N8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Fit", "Healthy"],
  },
  {
    id: 31,
    title: "Fitness 5",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Fitness",
    image:
      "https://images.unsplash.com/photo-1594737625785-a6cbdabd333c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MzR8fGZpdG5lc3N8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Fit", "Healthy"],
  },
  {
    id: 32,
    title: "Fitness 6",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Fitness",
    image:
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NDJ8fGZpdG5lc3N8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Fit", "Healthy"],
  },
  {
    id: 33,
    title: "Fitness 7",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Fitness",
    image:
      "https://images.unsplash.com/photo-1558611848-73f7eb4001a1?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NTh8fGZpdG5lc3N8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Fit", "Healthy"],
  },
  {
    id: 34,
    title: "Food 1",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Food",
    image:
      "https://images.unsplash.com/photo-1621241441637-ea2d3f59db32?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8Zm9vZCUyMGRlbGl2ZXJ5fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Food", "Tasty"],
  },
  {
    id: 35,
    title: "Food 2",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Food",
    image:
      "https://images.unsplash.com/photo-1483695028939-5bb13f8648b0?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTV8fGZvb2QlMjBkZWxpdmVyeXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Food", "Tasty"],
  },
  {
    id: 36,
    title: "Food 3",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Food",
    image:
      "https://images.unsplash.com/photo-1528510138849-786a5feddf94?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTd8fGZvb2QlMjBkZWxpdmVyeXxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Food", "Tasty"],
  },
  {
    id: 37,
    title: "Food 4",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Food",
    image:
      "https://images.unsplash.com/photo-1504674900247-0877df9cc836?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Zm9vZHxlbnwwfHwwfHw%3D&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Food", "Tasty"],
  },
  {
    id: 38,
    title: "Food 5",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Food",
    image:
      "https://images.unsplash.com/photo-1476224203421-9ac39bcb3327?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MTN8fGZvb2R8ZW58MHx8MHx8&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Food", "Tasty"],
  },
  {
    id: 38,
    title: "Food 6",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Food",
    image:
      "https://media.istockphoto.com/photos/foods-high-in-zinc-picture-id1289940519?b=1&k=20&m=1289940519&s=170667a&w=0&h=u5BwIDikkJCxrQQopgYHW2rOi7XBmG3JOHJJvYIE2C0=",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Food", "Tasty"],
  },
  {
    id: 38,
    title: "Food 7",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Food",
    image:
      "https://media.istockphoto.com/photos/classic-thai-food-dishes-picture-id1312283557?b=1&k=20&m=1312283557&s=170667a&w=0&h=hXAmitFiH9z0mK3GZdMDbkkcSl8Em84LIIlkHnVhpPE=",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Food", "Tasty"],
  },
  {
    id: 43,
    title: "Food 8",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Food",
    image:
      "https://images.unsplash.com/photo-1589010588553-46e8e7c21788?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8Zm9vZCUyMGRlbGl2ZXJ5fGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=600&q=60",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Food", "Tasty"],
  },
  {
    id: 44,
    title: "Fitness 8",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Fitness",
    image:
      "https://media.istockphoto.com/photos/fit-black-sporty-man-training-in-the-city-picture-id1295949061?b=1&k=20&m=1295949061&s=170667a&w=0&h=5tgauVHiZ6tw3LI6Wn7R6MAllwBbjDnqS_SWaUNcUmQ=",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Fit", "Healthy"],
  },
  {
    id: 45,
    title: "Hollywood 8",
    author: "Rajesh",
    read: "10 min read",
    claps: 200,
    category: "Hollywood",
    image:
      "https://images.unsplash.com/photo-1612036782180-6f0b6cd846fe?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=870&q=80",
    date: "January 1 2022",
    text: ` Occaecat est nostrud non sint officia reprehenderit commodo ea esse. Excepteur ullamco do in elit et culpa qui commodo Lorem consectetur occaecat. Enim adipisicing ut magna est excepteur et ullamco velit culpa ullamco ipsum qui dolore nostrud.`,
    tags: ["Hollywood", "English"],
  },
];

export default Blogs;
